### ISSUE TITLE
lost `patchparser-data` folder

### ISSUE THREAD

**Issue by 007gzs** [s3c2/llm-vulnerable-functions#1]
I couldn't find the `patchparser-data` folder in the `data` folder. How can I obtain or generate it?

**Comment by tdunlap607** [comment]
Hey @007gzs, thank you for catching this! I apologize for the misstep; I believe the original data is a larger file and didn't push to GitHub. I'm currently out of town, but I'll get a condensed version of the patchparser data to the repo (or a Zenodo) by the end of the week.

If you're in a rush to get the data, you can use [patchparser](https://github.com/s3c2/llm-vulnerable-functions/blob/main/data/advisory-data/govulndb-2023-10-26.csv) to obtain the patch data from the commit links on the [associated GoVulnDB reports](https://github.com/s3c2/llm-vulnerable-functions/blob/main/data/advisory-data/govulndb-2023-10-26.csv).

**Comment by 007gzs** [comment]
Thank you for your reply. I am not sure about the selection of file fields. It would be great if the script used to generate the file could be uploaded to the repository, such as the script to generate the final-patchparser-data file, as well as the cot-generate-tp-example.py and cot-generate-fp-example.py files mentioned in the code, and others.

**Comment by tdunlap607** [comment]
No problem! And acknowledged. I'll provide more info and feedback by the end of the week once I return from travel :+1:

**Comment by 007gzs** [comment]
Excuse me.  Have you had a chance to upload the data or scripts to the repository or make them available elsewhere?

**Comment by tdunlap607** [comment]
Hi @007gzs, I have added the data and scripts.

The data can be found here in the repo [/data/patchparser-data.tar.gz:](https://github.com/s3c2/llm-vulnerable-functions/blob/main/data/patchparser-data.tar.gz)

You can extract it like this:
```
mkdir ./data/patchparser-data
tar -xzf ./data/patchparser-data.tar.gz -C ./data/patchparser-data/
```
You'll then find these files:

```
$ ls ./data/patchparser-data
govulndb-cot-examples-fp-2023-10-31.csv  
govulndb-cot-examples-tp-2023-10-31.csv  
patchparser-data-2023-10-31.csv
```


The scripts for govulndb-cot-examples are here:
- [/code/llm/cot-generate-fp-example.py](https://github.com/s3c2/llm-vulnerable-functions/blob/main/code/llm/cot-generate-fp-example.py)
- [/code/llm/cot-generate-tp-example.py](https://github.com/s3c2/llm-vulnerable-functions/blob/main/code/llm/cot-generate-tp-example.py)

The headers contain instructions for running those scripts. Make sure you follow the instructions in the [README](https://github.com/s3c2/llm-vulnerable-functions/tree/main?tab=readme-ov-file#setup-instructions) to download and update the [cfg files](https://github.com/s3c2/llm-vulnerable-functions/tree/main/code/llm/cfgs). But you don't have to run them if you don't like since I have already generated the data for you. 

I executed each script to ensure everything worked as expected without any issues. I'm also happy to chat more about research directions with vulnerable functions or if you encounter other issues. Feel free to message me on [LinkedIn](https://www.linkedin.com/in/tdunlap607/), and we could schedule a meeting to chat!  Thanks :)

**Comment by 007gzs** [comment]
Thank you very much. I will try to test this project
